---
name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run ESLint
        run: npm run lint

      - name: Build Next.js
        run: npm run build
        env:
          SKIP_ENV_VALIDATION: true
          CI: true
          NODE_ENV: production
          # Add basic required env vars for build
          AUTH_SECRET: "test-secret-for-ci-build-only"
          XAI_API_KEY: "test-key"
          BLOB_READ_WRITE_TOKEN: "test-token"
          POSTGRES_URL: "postgresql://test:test@localhost:5432/test"
          REDIS_URL: "redis://localhost:6379"

  e2e:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: catalyst_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Get Playwright version
        id: playwright-version
        run: >
          echo "version=$(node -p
          "require('./package.json').devDependencies['@playwright/test']
          .replace('^', '')")" >> $GITHUB_OUTPUT

      - name: Cache playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: >
            ${{ runner.os }}-playwright-${{
            steps.playwright-version.outputs.version }}

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test
        env:
          MOCKED: 1
          DATABASE_URL: >
            postgresql://postgres:postgres@localhost:5432/catalyst_test
          SKIP_ENV_VALIDATION: true
          # Add basic required env vars for tests
          AUTH_SECRET: "test-secret-for-ci-build-only"
          XAI_API_KEY: "test-key"
          BLOB_READ_WRITE_TOKEN: "test-token"
          POSTGRES_URL: >
            postgresql://postgres:postgres@localhost:5432/catalyst_test
          REDIS_URL: "redis://localhost:6379"

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: ./playwright-report/
          retention-days: 30

      - name: Upload test screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-screenshots
          path: ./test-results/**/test-failed-*.png
          retention-days: 30

      - name: Upload test videos
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-videos
          path: ./test-results/**/video.webm
          retention-days: 30
